from enum import Enum


class PaymentStatus(Enum):
    NEW = "NEW"
    FORM_SHOWED = "FORM_SHOWED"
    AUTHORIZING = "AUTHORIZING"
    THREEDS_CHECKING = "3DS_CHECKING"
    THREEDS_CHECKED = "3DS_CHECKED"
    AUTHORIZED = "AUTHORIZED"
    PAY_CHECKING = "PAY_CHECKING"
    CONFIRMING = "CONFIRMING"
    CONFIRMED = "CONFIRMED"
    REVERSING = "REVERSING"
    PARTIAL_REVERSED = "PARTIAL_REVERSED"
    REVERSED = "REVERSED"
    REFUNDING = "REFUNDING"
    PARTIAL_REFUNDED = "PARTIAL_REFUNDED"
    REFUNDED = "REFUNDED"
    CANCELLED = "CANCELLED"
    DEADLINE_EXPIRED = "DEADLINE_EXPIRED"
    REJECTED = "REJECTED"
    AUTH_FAIL = "AUTH_FAIL"

    @property
    def end_statuses(self):
        return [self.CONFIRMED, self.REJECTED, self.CANCELLED]
